from datetime import datetime, timezone
import uuid

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _uuid() -> str:
    return str(uuid.uuid4())


class Base(DeclarativeBase):
    pass


class Signal(Base):
    """One piece of news-derived market signal for a specific ticker."""

    __tablename__ = "signals"

    id = Column(String, primary_key=True, default=_uuid)
    ticker = Column(String, nullable=False, index=True)
    sentiment = Column(String, nullable=False)  # bullish | bearish | neutral
    confidence = Column(Float, nullable=False)   # 0.0 – 1.0
    source = Column(String, nullable=False)
    headline = Column(Text, nullable=False)
    raw_text = Column(Text)
    created_at = Column(DateTime, default=_now_utc)


class Thesis(Base):
    """A structured market thesis generated by the analysis agent."""

    __tablename__ = "theses"

    id = Column(String, primary_key=True, default=_uuid)
    ticker = Column(String, nullable=False, index=True)
    direction = Column(String, nullable=False)   # bullish | bearish | neutral
    confidence = Column(Float, nullable=False)   # 0.0 – 1.0
    timeframe = Column(String, nullable=False)   # e.g. "3-10 days"
    reasoning = Column(Text, nullable=False)
    key_risks = Column(Text, nullable=False)     # JSON-serialised list[str]
    created_at = Column(DateTime, default=_now_utc)
    resolved_at = Column(DateTime, nullable=True)
    outcome = Column(String, nullable=True)      # correct | incorrect | partial
    accuracy = Column(Float, nullable=True)      # price-change accuracy score


class TradeIdea(Base):
    """Actionable trade idea generated from a thesis — the bridge from analysis to execution."""
    __tablename__ = "trade_ideas"

    id = Column(String, primary_key=True, default=_uuid)
    thesis_id = Column(String, ForeignKey("theses.id"), nullable=False)
    ticker = Column(String, nullable=False, index=True)

    # Direction & strategy
    direction = Column(String, nullable=False)       # long | short
    strategy = Column(String, nullable=False)         # equity_long | equity_short | hold | avoid
    horizon = Column(String, nullable=False)          # short (1-5d) | medium (1-4w) | long (1-3m)

    # Price levels
    entry_price = Column(Float, nullable=False)       # suggested entry price
    stop_loss = Column(Float, nullable=False)          # stop-loss price
    take_profit = Column(Float, nullable=False)        # take-profit target
    current_price = Column(Float, nullable=False)      # price at time of generation

    # Sizing & risk
    confidence = Column(Float, nullable=False)         # 0.0-1.0 from thesis
    risk_reward_ratio = Column(Float, nullable=False)  # reward / risk
    position_size_pct = Column(Float, nullable=False)  # % of portfolio to allocate
    max_loss_pct = Column(Float, nullable=False)       # max loss as % of portfolio

    # Rationale
    rationale = Column(Text, nullable=False)           # why this trade, in plain language
    key_levels = Column(Text)                          # JSON: support/resistance levels

    # Lifecycle
    status = Column(String, default="active")          # active | executed | expired | cancelled
    created_at = Column(DateTime, default=_now_utc)
    expires_at = Column(DateTime, nullable=True)       # when the idea becomes stale
    executed_at = Column(DateTime, nullable=True)


class ChatMessage(Base):
    """Persistent message from a coach conversation session."""

    __tablename__ = "chat_messages"

    id = Column(String, primary_key=True, default=_uuid)
    session_id = Column(String, nullable=False, index=True)
    role = Column(String, nullable=False)        # user | assistant
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=_now_utc)


class Position(Base):
    """A paper or live position managed through Alpaca."""

    __tablename__ = "positions"

    id = Column(String, primary_key=True, default=_uuid)
    ticker = Column(String, nullable=False)
    qty = Column(Float, nullable=False)
    entry_price = Column(Float, nullable=False)
    entry_thesis_id = Column(String, ForeignKey("theses.id"), nullable=True)
    broker = Column(String, default="alpaca")
    is_paper = Column(Boolean, default=True)
    created_at = Column(DateTime, default=_now_utc)


class UserMemory(Base):
    """Persistent user context that spans sessions — risk tolerance, preferences, observations."""

    __tablename__ = "user_memories"

    id = Column(String, primary_key=True, default=_uuid)
    key = Column(String, nullable=False, index=True)  # e.g. "risk_tolerance", "sector_interest", "observation"
    value = Column(Text, nullable=False)
    category = Column(String, nullable=False, default="general")  # profile | observation | preference
    created_at = Column(DateTime, default=_now_utc)
    updated_at = Column(DateTime, default=_now_utc, onupdate=_now_utc)


class AutoRule(Base):
    """
    Automation rule for paper-trading execution.
    Rules are paper-only by default. Live requires explicit opt-in.
    """

    __tablename__ = "auto_rules"

    id = Column(String, primary_key=True, default=_uuid)
    condition_expr = Column(Text, nullable=False)  # e.g. "confidence > 0.80 AND direction == 'bullish'"
    action = Column(String, nullable=False)         # buy | sell
    size_pct = Column(Float, nullable=False)        # % of portfolio to use
    max_per_day = Column(Integer, default=1)
    paper_only = Column(Boolean, default=True)      # ALWAYS true unless user opts in
    active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=_now_utc)


class PriceAlert(Base):
    """
    A price-level alert on a ticker. Watches a current price and fires a
    notification (persisted as a news_reactions row with trigger_reason=
    'price_alert') when the condition is met.

    V1 conditions:
      - "above" → fires when current_price >= target_price
      - "below" → fires when current_price <= target_price

    V1 is one-shot: once triggered, the alert is marked inactive and
    won't fire again. The user can explicitly re-arm by creating a new
    alert. Avoids the "crosses above/below" edge case (requires knowing
    the previous polled price) which belongs in v2.

    The `note` field lets the user capture WHY they're watching this level
    ("resistance for GLD trim", "support for TSLA entry") so future-them
    reading the triggered notification remembers the context.
    """

    __tablename__ = "price_alerts"

    id = Column(String, primary_key=True, default=_uuid)
    ticker = Column(String, nullable=False, index=True)
    condition = Column(String, nullable=False)  # above | below
    target_price = Column(Float, nullable=False)
    note = Column(Text, nullable=True)
    active = Column(Boolean, nullable=False, default=True, index=True)
    created_at = Column(DateTime, default=_now_utc)
    triggered_at = Column(DateTime, nullable=True)
    triggered_price = Column(Float, nullable=True)


class WatchlistTicker(Base):
    """
    A ticker on the user's watchlist.

    The watchlist gates which tickers the /orders/confirm endpoint will
    actually submit (positions ∪ open theses ∪ watchlist). It's also the
    seed list for the news intelligence pipeline — every 4h the news
    agent fetches news for these tickers.

    Historically the watchlist lived in DEFAULT_WATCHLIST in .env as a
    comma-separated string. That meant adding a new ticker required
    editing .env and restarting the backend, which hit us the first time
    the user wanted to trade GLD. Now it's a proper table — env stays as
    the initial seed for first-run installs, but all runtime reads go
    through this model so the user can add/remove from the UI without
    restarting anything.
    """

    __tablename__ = "watchlist"

    ticker = Column(String, primary_key=True)  # uppercase, unique
    notes = Column(Text, nullable=True)         # optional "why I'm watching"
    added_at = Column(DateTime, default=_now_utc)


class TradeJournalEntry(Base):
    """
    A user-owned trade journal entry. Captures the full lifecycle of one
    position: entry, the user's own thesis (in their own words, required),
    the advisor's rationale if there was one, the close, and the user's
    lesson learned after the fact.

    Why this model exists separately from ExecutedOrder:
      - ExecutedOrder is an audit trail of what happened ("MarketCoach
        submitted these orders"). It's a system record.
      - TradeJournalEntry is a reflection record. It pairs the system's
        view of the trade with the user's reasoning at decision time and
        their learning after the outcome is known.

    The whole point is the discipline. The user_thesis MUST be filled in
    before an order placed via /orders/confirm is allowed to execute, and
    the user_lesson MUST be filled in after the position closes for the
    entry to count as 'complete'. Half-filled entries surface as 'action
    needed' in the Journal UI until the user finishes them.

    Manual trades placed directly in Alpaca/IBKR (bypassing the Execute
    button) are detected by the position polling job and inserted with
    needs_thesis=True so the user can fill in the reasoning after the fact.
    Less ideal than capturing it before execution, but better than nothing.
    """

    __tablename__ = "trade_journal_entries"

    id = Column(String, primary_key=True, default=_uuid)

    # Optional links to the executed-order rows that opened/closed the trade.
    # Both are nullable because manual trades have no MarketCoach order record.
    open_executed_order_id = Column(
        String, ForeignKey("executed_orders.id"), nullable=True
    )
    close_executed_order_id = Column(
        String, ForeignKey("executed_orders.id"), nullable=True
    )

    # Trade identity
    ticker = Column(String, nullable=False, index=True)
    side = Column(String, nullable=False)         # buy | sell — direction at open
    qty = Column(Float, nullable=False)

    # Open
    open_price = Column(Float, nullable=False)
    opened_at = Column(DateTime, nullable=False)

    # User input (open) — the discipline lives here
    user_thesis = Column(Text, nullable=True)            # in their own words
    user_disagreement = Column(Text, nullable=True)      # vs the advisor, optional

    # Advisor context — only present when the trade came from a chat
    # recommendation (rationale was on the OrderConfirmRequest).
    advisor_session_id = Column(String, nullable=True)
    advisor_rationale = Column(Text, nullable=True)

    # Close
    close_price = Column(Float, nullable=True)
    closed_at = Column(DateTime, nullable=True)
    pnl_amount = Column(Float, nullable=True)
    pnl_pct = Column(Float, nullable=True)
    days_held = Column(Integer, nullable=True)
    advised_direction_profitable = Column(Boolean, nullable=True)

    # User input (close) — the lesson learned
    user_lesson = Column(Text, nullable=True)

    # Status: open or closed. Whether action is needed is derived from
    # presence of user_thesis (when open) and user_lesson (when closed).
    status = Column(String, nullable=False, default="open", index=True)
    created_at = Column(DateTime, default=_now_utc)


class EquitySnapshot(Base):
    """
    Periodic snapshot of the account's equity / buying power / cash.

    Written once per position-poll cycle (default 5 minutes) so the
    Dashboard can render an equity curve over time. One row per poll,
    NOT one row per ticker — that's the difference from PositionSnapshot.

    The chart's resolution is bounded by the polling interval. 5 min
    means ~288 points per day, ~2000 per week. Plenty for a line chart
    without being wasteful.
    """

    __tablename__ = "equity_snapshots"

    id = Column(String, primary_key=True, default=_uuid)
    equity = Column(Float, nullable=False)
    buying_power = Column(Float, nullable=True)
    cash = Column(Float, nullable=True)
    portfolio_value = Column(Float, nullable=True)
    snapshot_at = Column(DateTime, default=_now_utc, index=True)


class PositionSnapshot(Base):
    """
    Periodic snapshot of one position at a point in time. Written by the
    position-change polling job so the next poll can diff against it.

    We keep a row per (ticker, snapshot_at) rather than overwriting because:
      - Restart-safe: the polling loop reads the latest snapshot per ticker
      - Auditable: history is right there if we ever want to chart P&L over
        time without paying for a market-data subscription
      - Cheap: a few hundred rows/day for a small portfolio is nothing in SQLite

    Closed positions are still represented — we write a row with qty=0 the
    first time a previously-held ticker disappears, then stop emitting until
    it comes back. That's how the diff knows the close was already handled.
    """

    __tablename__ = "position_snapshots"

    id = Column(String, primary_key=True, default=_uuid)
    ticker = Column(String, nullable=False, index=True)
    qty = Column(Float, nullable=False)
    avg_entry = Column(Float, nullable=True)
    current_price = Column(Float, nullable=True)
    unrealised_pnl_pct = Column(Float, nullable=True)
    snapshot_at = Column(DateTime, default=_now_utc, index=True)


class ExecutedOrder(Base):
    """
    Audit trail of orders MarketCoach placed on the user's behalf.

    Distinct from the Position model (which tracks current holdings) and from
    Alpaca's own order history (which we don't control). Every confirmed
    execute click — accepted OR rejected — gets a row here so the user has
    a single source of truth for what THIS app did with their account.

    Includes the rationale and originating advisor session so each trade
    is traceable back to the conversation that produced it.
    """

    __tablename__ = "executed_orders"

    id = Column(String, primary_key=True, default=_uuid)
    alpaca_order_id = Column(String, nullable=True)   # null when our gate rejected before submitting
    ticker = Column(String, nullable=False, index=True)
    side = Column(String, nullable=False)              # buy | sell
    qty = Column(Float, nullable=False)
    order_type = Column(String, nullable=False)        # market | limit
    # order_class distinguishes plain single-leg orders from bracket entries.
    # Nullable because historical rows predate the column — treat null as
    # "simple" when reading.
    order_class = Column(String, nullable=True)         # simple | bracket | null (legacy=simple)
    limit_price = Column(Float, nullable=True)
    # Bracket-only: the attached stop-loss and take-profit levels submitted
    # with the parent order. Stored for the audit trail only — once the
    # order is live the broker owns the OCO group, not us.
    stop_loss_price = Column(Float, nullable=True)
    take_profit_price = Column(Float, nullable=True)
    fill_price = Column(Float, nullable=True)
    status = Column(String, nullable=False, index=True)  # accepted | filled | rejected | failed
    rejection_reason = Column(Text, nullable=True)
    is_paper = Column(Boolean, default=True)
    rationale = Column(Text, nullable=True)
    advisor_session_id = Column(String, nullable=True, index=True)
    submitted_at = Column(DateTime, nullable=True)
    filled_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=_now_utc, index=True)


class NewsReaction(Base):
    """
    An auto-generated TradingAdvisor reaction to a high-impact news signal.

    Created by the intelligence pipeline when a signal crosses the impact
    threshold AND affects a position, open thesis, or watchlist ticker.
    Surfaced in the UI as a notification — the user marks it read or dismissed.
    """

    __tablename__ = "news_reactions"

    id = Column(String, primary_key=True, default=_uuid)
    signal_id = Column(String, ForeignKey("signals.id"), nullable=True, index=True)
    ticker = Column(String, nullable=False, index=True)
    headline = Column(Text, nullable=False)
    content = Column(Text, nullable=False)            # markdown reaction from the advisor
    trigger_reason = Column(String, nullable=False)   # position | thesis | watchlist
    status = Column(String, default="unread", index=True)  # unread | read | dismissed
    error = Column(Text, nullable=True)
    created_at = Column(DateTime, default=_now_utc, index=True)


class WeeklyPlan(Base):
    """A generated weekly trading plan from the TradingAdvisorAgent."""

    __tablename__ = "weekly_plans"

    id = Column(String, primary_key=True, default=_uuid)
    session_id = Column(String, nullable=False, index=True)
    content = Column(Text, nullable=False)           # full markdown plan from the advisor
    status = Column(String, default="completed")      # completed | failed
    error = Column(Text, nullable=True)
    trigger = Column(String, default="scheduled")     # scheduled | manual
    created_at = Column(DateTime, default=_now_utc, index=True)


class MorningBrief(Base):
    """
    A daily pre-market brief from the TradingAdvisorAgent.

    Generated weekday mornings (default 06:00 local) so it's ready before
    the user wakes up. Focused and short — overnight news, today's earnings,
    premarket movers, action items. Designed to be read on a phone in bed.
    """

    __tablename__ = "morning_briefs"

    id = Column(String, primary_key=True, default=_uuid)
    session_id = Column(String, nullable=False, index=True)
    content = Column(Text, nullable=False)
    status = Column(String, default="completed")     # completed | failed
    error = Column(Text, nullable=True)
    trigger = Column(String, default="scheduled")    # scheduled | manual
    created_at = Column(DateTime, default=_now_utc, index=True)


class BacktestRun(Base):
    """
    Persisted backtest result — stores the full config and output as JSON
    so we can review past runs without re-executing.
    """

    __tablename__ = "backtest_runs"

    id = Column(String, primary_key=True, default=_uuid)
    config_json = Column(Text, nullable=False)    # JSON-serialized BacktestConfig
    result_json = Column(Text, nullable=False)    # JSON-serialized BacktestResult
    status = Column(String, default="completed")  # completed | failed
    initial_capital = Column(Float, nullable=False)
    final_equity = Column(Float, nullable=True)
    total_return_pct = Column(Float, nullable=True)
    total_trades = Column(Integer, nullable=True)
    win_rate_pct = Column(Float, nullable=True)
    max_drawdown_pct = Column(Float, nullable=True)
    started_at = Column(DateTime, nullable=False)
    completed_at = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=_now_utc)
