from datetime import datetime, timezone
import uuid

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import DeclarativeBase


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def _uuid() -> str:
    return str(uuid.uuid4())


class Base(DeclarativeBase):
    pass


class Signal(Base):
    """One piece of news-derived market signal for a specific ticker."""

    __tablename__ = "signals"

    id = Column(String, primary_key=True, default=_uuid)
    ticker = Column(String, nullable=False, index=True)
    sentiment = Column(String, nullable=False)  # bullish | bearish | neutral
    confidence = Column(Float, nullable=False)   # 0.0 – 1.0
    source = Column(String, nullable=False)
    headline = Column(Text, nullable=False)
    raw_text = Column(Text)
    created_at = Column(DateTime, default=_now_utc)


class Thesis(Base):
    """A structured market thesis generated by the analysis agent."""

    __tablename__ = "theses"

    id = Column(String, primary_key=True, default=_uuid)
    ticker = Column(String, nullable=False, index=True)
    direction = Column(String, nullable=False)   # bullish | bearish | neutral
    confidence = Column(Float, nullable=False)   # 0.0 – 1.0
    timeframe = Column(String, nullable=False)   # e.g. "3-10 days"
    reasoning = Column(Text, nullable=False)
    key_risks = Column(Text, nullable=False)     # JSON-serialised list[str]
    created_at = Column(DateTime, default=_now_utc)
    resolved_at = Column(DateTime, nullable=True)
    outcome = Column(String, nullable=True)      # correct | incorrect | partial
    accuracy = Column(Float, nullable=True)      # price-change accuracy score


class TradeIdea(Base):
    """Actionable trade idea generated from a thesis — the bridge from analysis to execution."""
    __tablename__ = "trade_ideas"

    id = Column(String, primary_key=True, default=_uuid)
    thesis_id = Column(String, ForeignKey("theses.id"), nullable=False)
    ticker = Column(String, nullable=False, index=True)

    # Direction & strategy
    direction = Column(String, nullable=False)       # long | short
    strategy = Column(String, nullable=False)         # equity_long | equity_short | hold | avoid
    horizon = Column(String, nullable=False)          # short (1-5d) | medium (1-4w) | long (1-3m)

    # Price levels
    entry_price = Column(Float, nullable=False)       # suggested entry price
    stop_loss = Column(Float, nullable=False)          # stop-loss price
    take_profit = Column(Float, nullable=False)        # take-profit target
    current_price = Column(Float, nullable=False)      # price at time of generation

    # Sizing & risk
    confidence = Column(Float, nullable=False)         # 0.0-1.0 from thesis
    risk_reward_ratio = Column(Float, nullable=False)  # reward / risk
    position_size_pct = Column(Float, nullable=False)  # % of portfolio to allocate
    max_loss_pct = Column(Float, nullable=False)       # max loss as % of portfolio

    # Rationale
    rationale = Column(Text, nullable=False)           # why this trade, in plain language
    key_levels = Column(Text)                          # JSON: support/resistance levels

    # Lifecycle
    status = Column(String, default="active")          # active | executed | expired | cancelled
    created_at = Column(DateTime, default=_now_utc)
    expires_at = Column(DateTime, nullable=True)       # when the idea becomes stale
    executed_at = Column(DateTime, nullable=True)


class ChatMessage(Base):
    """Persistent message from a coach conversation session."""

    __tablename__ = "chat_messages"

    id = Column(String, primary_key=True, default=_uuid)
    session_id = Column(String, nullable=False, index=True)
    role = Column(String, nullable=False)        # user | assistant
    content = Column(Text, nullable=False)
    created_at = Column(DateTime, default=_now_utc)


class Position(Base):
    """A paper or live position managed through Alpaca."""

    __tablename__ = "positions"

    id = Column(String, primary_key=True, default=_uuid)
    ticker = Column(String, nullable=False)
    qty = Column(Float, nullable=False)
    entry_price = Column(Float, nullable=False)
    entry_thesis_id = Column(String, ForeignKey("theses.id"), nullable=True)
    broker = Column(String, default="alpaca")
    is_paper = Column(Boolean, default=True)
    created_at = Column(DateTime, default=_now_utc)


class UserMemory(Base):
    """Persistent user context that spans sessions — risk tolerance, preferences, observations."""

    __tablename__ = "user_memories"

    id = Column(String, primary_key=True, default=_uuid)
    key = Column(String, nullable=False, index=True)  # e.g. "risk_tolerance", "sector_interest", "observation"
    value = Column(Text, nullable=False)
    category = Column(String, nullable=False, default="general")  # profile | observation | preference
    created_at = Column(DateTime, default=_now_utc)
    updated_at = Column(DateTime, default=_now_utc, onupdate=_now_utc)


class AutoRule(Base):
    """
    Automation rule for paper-trading execution.
    Rules are paper-only by default. Live requires explicit opt-in.
    """

    __tablename__ = "auto_rules"

    id = Column(String, primary_key=True, default=_uuid)
    condition_expr = Column(Text, nullable=False)  # e.g. "confidence > 0.80 AND direction == 'bullish'"
    action = Column(String, nullable=False)         # buy | sell
    size_pct = Column(Float, nullable=False)        # % of portfolio to use
    max_per_day = Column(Integer, default=1)
    paper_only = Column(Boolean, default=True)      # ALWAYS true unless user opts in
    active = Column(Boolean, default=True)
    created_at = Column(DateTime, default=_now_utc)


class PositionSnapshot(Base):
    """
    Periodic snapshot of one position at a point in time. Written by the
    position-change polling job so the next poll can diff against it.

    We keep a row per (ticker, snapshot_at) rather than overwriting because:
      - Restart-safe: the polling loop reads the latest snapshot per ticker
      - Auditable: history is right there if we ever want to chart P&L over
        time without paying for a market-data subscription
      - Cheap: a few hundred rows/day for a small portfolio is nothing in SQLite

    Closed positions are still represented — we write a row with qty=0 the
    first time a previously-held ticker disappears, then stop emitting until
    it comes back. That's how the diff knows the close was already handled.
    """

    __tablename__ = "position_snapshots"

    id = Column(String, primary_key=True, default=_uuid)
    ticker = Column(String, nullable=False, index=True)
    qty = Column(Float, nullable=False)
    avg_entry = Column(Float, nullable=True)
    current_price = Column(Float, nullable=True)
    unrealised_pnl_pct = Column(Float, nullable=True)
    snapshot_at = Column(DateTime, default=_now_utc, index=True)


class ExecutedOrder(Base):
    """
    Audit trail of orders MarketCoach placed on the user's behalf.

    Distinct from the Position model (which tracks current holdings) and from
    Alpaca's own order history (which we don't control). Every confirmed
    execute click — accepted OR rejected — gets a row here so the user has
    a single source of truth for what THIS app did with their account.

    Includes the rationale and originating advisor session so each trade
    is traceable back to the conversation that produced it.
    """

    __tablename__ = "executed_orders"

    id = Column(String, primary_key=True, default=_uuid)
    alpaca_order_id = Column(String, nullable=True)   # null when our gate rejected before submitting
    ticker = Column(String, nullable=False, index=True)
    side = Column(String, nullable=False)              # buy | sell
    qty = Column(Float, nullable=False)
    order_type = Column(String, nullable=False)        # market | limit
    limit_price = Column(Float, nullable=True)
    fill_price = Column(Float, nullable=True)
    status = Column(String, nullable=False, index=True)  # accepted | filled | rejected | failed
    rejection_reason = Column(Text, nullable=True)
    is_paper = Column(Boolean, default=True)
    rationale = Column(Text, nullable=True)
    advisor_session_id = Column(String, nullable=True, index=True)
    submitted_at = Column(DateTime, nullable=True)
    filled_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=_now_utc, index=True)


class NewsReaction(Base):
    """
    An auto-generated TradingAdvisor reaction to a high-impact news signal.

    Created by the intelligence pipeline when a signal crosses the impact
    threshold AND affects a position, open thesis, or watchlist ticker.
    Surfaced in the UI as a notification — the user marks it read or dismissed.
    """

    __tablename__ = "news_reactions"

    id = Column(String, primary_key=True, default=_uuid)
    signal_id = Column(String, ForeignKey("signals.id"), nullable=True, index=True)
    ticker = Column(String, nullable=False, index=True)
    headline = Column(Text, nullable=False)
    content = Column(Text, nullable=False)            # markdown reaction from the advisor
    trigger_reason = Column(String, nullable=False)   # position | thesis | watchlist
    status = Column(String, default="unread", index=True)  # unread | read | dismissed
    error = Column(Text, nullable=True)
    created_at = Column(DateTime, default=_now_utc, index=True)


class WeeklyPlan(Base):
    """A generated weekly trading plan from the TradingAdvisorAgent."""

    __tablename__ = "weekly_plans"

    id = Column(String, primary_key=True, default=_uuid)
    session_id = Column(String, nullable=False, index=True)
    content = Column(Text, nullable=False)           # full markdown plan from the advisor
    status = Column(String, default="completed")      # completed | failed
    error = Column(Text, nullable=True)
    trigger = Column(String, default="scheduled")     # scheduled | manual
    created_at = Column(DateTime, default=_now_utc, index=True)


class MorningBrief(Base):
    """
    A daily pre-market brief from the TradingAdvisorAgent.

    Generated weekday mornings (default 06:00 local) so it's ready before
    the user wakes up. Focused and short — overnight news, today's earnings,
    premarket movers, action items. Designed to be read on a phone in bed.
    """

    __tablename__ = "morning_briefs"

    id = Column(String, primary_key=True, default=_uuid)
    session_id = Column(String, nullable=False, index=True)
    content = Column(Text, nullable=False)
    status = Column(String, default="completed")     # completed | failed
    error = Column(Text, nullable=True)
    trigger = Column(String, default="scheduled")    # scheduled | manual
    created_at = Column(DateTime, default=_now_utc, index=True)


class BacktestRun(Base):
    """
    Persisted backtest result — stores the full config and output as JSON
    so we can review past runs without re-executing.
    """

    __tablename__ = "backtest_runs"

    id = Column(String, primary_key=True, default=_uuid)
    config_json = Column(Text, nullable=False)    # JSON-serialized BacktestConfig
    result_json = Column(Text, nullable=False)    # JSON-serialized BacktestResult
    status = Column(String, default="completed")  # completed | failed
    initial_capital = Column(Float, nullable=False)
    final_equity = Column(Float, nullable=True)
    total_return_pct = Column(Float, nullable=True)
    total_trades = Column(Integer, nullable=True)
    win_rate_pct = Column(Float, nullable=True)
    max_drawdown_pct = Column(Float, nullable=True)
    started_at = Column(DateTime, nullable=False)
    completed_at = Column(DateTime, nullable=False)
    created_at = Column(DateTime, default=_now_utc)
