import { useState, useEffect } from 'react'
import axios from 'axios'
import ReactMarkdown from 'react-markdown'

const API = '/api'

const STATUS_TABS = [
  { id: 'unread', label: 'Unread' },
  { id: 'read', label: 'Read' },
  { id: 'dismissed', label: 'Dismissed' },
  { id: null, label: 'All' },
]

const TRIGGER_LABELS = {
  // News-driven categories (from the intelligence pipeline filter)
  position: { label: 'POSITION', color: 'bg-red-900/40 border-red-700 text-red-200' },
  thesis: { label: 'THESIS', color: 'bg-amber-900/40 border-amber-700 text-amber-200' },
  watchlist: { label: 'WATCHLIST', color: 'bg-gray-800 border-gray-700 text-gray-300' },
  // Position-change categories (from the position polling job)
  position_opened: { label: 'OPENED', color: 'bg-emerald-900/40 border-emerald-700 text-emerald-200' },
  position_closed: { label: 'CLOSED', color: 'bg-blue-900/40 border-blue-700 text-blue-200' },
  position_changed: { label: 'CHANGED', color: 'bg-indigo-900/40 border-indigo-700 text-indigo-200' },
  pnl_threshold: { label: 'P&L MOVE', color: 'bg-purple-900/40 border-purple-700 text-purple-200' },
}

function formatTimestamp(iso) {
  if (!iso) return ''
  try {
    return new Date(iso).toLocaleString()
  } catch {
    return iso
  }
}

export default function NewsReactions() {
  const [reactions, setReactions] = useState([])
  const [statusFilter, setStatusFilter] = useState('unread')
  const [expandedId, setExpandedId] = useState(null)
  const [loading, setLoading] = useState(true)

  const fetchReactions = async (filter) => {
    setLoading(true)
    try {
      const params = filter ? `?status=${filter}` : ''
      const res = await axios.get(`${API}/news-reactions${params}`)
      setReactions(res.data || [])
    } catch (err) {
      console.error('Failed to fetch reactions:', err)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchReactions(statusFilter)
  }, [statusFilter])

  const markRead = async (id, e) => {
    e?.stopPropagation()
    try {
      await axios.post(`${API}/news-reactions/${id}/read`)
      fetchReactions(statusFilter)
    } catch (err) {
      console.error('Failed to mark read:', err)
    }
  }

  const dismiss = async (id, e) => {
    e?.stopPropagation()
    try {
      await axios.post(`${API}/news-reactions/${id}/dismiss`)
      fetchReactions(statusFilter)
    } catch (err) {
      console.error('Failed to dismiss:', err)
    }
  }

  const toggleExpand = (reaction) => {
    if (expandedId === reaction.id) {
      setExpandedId(null)
    } else {
      setExpandedId(reaction.id)
      // Auto-mark-read when opening an unread item
      if (reaction.status === 'unread') {
        markRead(reaction.id)
      }
    }
  }

  return (
    <div className="max-w-4xl mx-auto">
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-white">Notifications</h1>
        <p className="text-sm text-gray-400 mt-1">
          Auto-generated by the trading advisor when something needs your
          attention — high-impact news on your tickers, or position changes
          (opened, closed, big P&amp;L moves). Runs every few minutes.
        </p>
      </div>

      <div className="flex gap-2 mb-4 border-b border-gray-800">
        {STATUS_TABS.map((tab) => (
          <button
            key={tab.id || 'all'}
            onClick={() => setStatusFilter(tab.id)}
            className={`px-4 py-2 text-sm font-medium transition-colors ${
              statusFilter === tab.id
                ? 'text-white border-b-2 border-indigo-500 -mb-px'
                : 'text-gray-400 hover:text-gray-200'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {loading ? (
        <div className="text-gray-400 text-sm">Loading…</div>
      ) : reactions.length === 0 ? (
        <div className="bg-gray-900 border border-gray-800 rounded-lg p-8 text-center text-gray-400">
          <p className="text-sm">No reactions in this view.</p>
          <p className="text-xs mt-2 text-gray-500">
            New reactions appear after the intelligence pipeline runs (every
            4h) when signals cross the impact threshold.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {reactions.map((r) => {
            const trigger = TRIGGER_LABELS[r.trigger_reason] || TRIGGER_LABELS.watchlist
            const expanded = expandedId === r.id
            const isFailed = r.status === 'failed'
            return (
              <div
                key={r.id}
                onClick={() => toggleExpand(r)}
                className={`bg-gray-900 border rounded-lg p-4 cursor-pointer transition-colors ${
                  r.status === 'unread'
                    ? 'border-indigo-700/50 hover:border-indigo-600'
                    : 'border-gray-800 hover:border-gray-700'
                }`}
              >
                <div className="flex items-start justify-between gap-3 mb-2">
                  <div className="flex items-center gap-2 flex-1 min-w-0">
                    <span className="font-bold text-white">{r.ticker}</span>
                    <span
                      className={`text-xs px-2 py-0.5 rounded border ${trigger.color}`}
                    >
                      {trigger.label}
                    </span>
                    {r.status === 'unread' && (
                      <span className="w-2 h-2 rounded-full bg-indigo-400" />
                    )}
                    {isFailed && (
                      <span className="text-xs text-red-400">FAILED</span>
                    )}
                  </div>
                  <span className="text-xs text-gray-500 shrink-0">
                    {formatTimestamp(r.created_at)}
                  </span>
                </div>

                <p className="text-sm text-gray-300 line-clamp-2">{r.headline}</p>

                {expanded && (
                  <div className="mt-4 pt-4 border-t border-gray-800">
                    {isFailed ? (
                      <div className="text-sm text-red-300">
                        Generation failed: {r.error || 'unknown error'}
                      </div>
                    ) : (
                      <div className="prose prose-invert prose-sm max-w-none">
                        <ReactMarkdown>{r.content}</ReactMarkdown>
                      </div>
                    )}
                    <div className="mt-4 flex gap-2">
                      {r.status !== 'dismissed' && (
                        <button
                          onClick={(e) => dismiss(r.id, e)}
                          className="px-3 py-1 text-xs bg-gray-800 hover:bg-gray-700 text-gray-300 rounded"
                        >
                          Dismiss
                        </button>
                      )}
                      {r.status === 'unread' && (
                        <button
                          onClick={(e) => markRead(r.id, e)}
                          className="px-3 py-1 text-xs bg-indigo-700 hover:bg-indigo-600 text-white rounded"
                        >
                          Mark read
                        </button>
                      )}
                    </div>
                  </div>
                )}
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}
